// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjt6RhUygBjy1vB_VXOXy99Ao_Xn6Log',
    appId: '1:90142825030:web:5ececa082ff933e0528847',
    messagingSenderId: '90142825030',
    projectId: 'timelineapp-87f4d',
    authDomain: 'timelineapp-87f4d.firebaseapp.com',
    databaseURL: 'https://timelineapp-87f4d-default-rtdb.firebaseio.com',
    storageBucket: 'timelineapp-87f4d.appspot.com',
    measurementId: 'G-1BQHTM8RK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjE-5JxkLmYa00dj2rvxHoiAUwA8u_fUw',
    appId: '1:90142825030:android:7527983420e43b4e528847',
    messagingSenderId: '90142825030',
    projectId: 'timelineapp-87f4d',
    databaseURL: 'https://timelineapp-87f4d-default-rtdb.firebaseio.com',
    storageBucket: 'timelineapp-87f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXkXlmntencn3NUxyqt703ZpptzdCAQY',
    appId: '1:90142825030:ios:dcbff2cfc58a52cb528847',
    messagingSenderId: '90142825030',
    projectId: 'timelineapp-87f4d',
    databaseURL: 'https://timelineapp-87f4d-default-rtdb.firebaseio.com',
    storageBucket: 'timelineapp-87f4d.appspot.com',
    iosClientId: '90142825030-03kcbi93pk0vf7cf9hht2v6dpa5qo1tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.timelineapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxXkXlmntencn3NUxyqt703ZpptzdCAQY',
    appId: '1:90142825030:ios:dcbff2cfc58a52cb528847',
    messagingSenderId: '90142825030',
    projectId: 'timelineapp-87f4d',
    databaseURL: 'https://timelineapp-87f4d-default-rtdb.firebaseio.com',
    storageBucket: 'timelineapp-87f4d.appspot.com',
    iosClientId: '90142825030-03kcbi93pk0vf7cf9hht2v6dpa5qo1tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.timelineapp',
  );
}
